name: Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy-prod:
    if: github.ref_name == 'master'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy repo to production directory 
        run: cp -r ./* /opt/apps_docker/apps/prod/front_prod
      - name: Rebuild docker-compose
        run: docker-compose -f /opt/apps_docker/docker-compose.yml up -d --build front-prod 

  deploy-dev:
    if: github.ref_name == 'dev'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy repo to development directory 
        run: cp -r ./* /opt/apps_docker/apps/dev/front_dev
      - name: Rebuild docker-compose
        run: docker-compose -f /opt/apps_docker/docker-compose.yml up -d --build front-dev
